# Section 1 — Python Fundamentals & Pandas Basics
**Course:** Data Mining (Information Systems, Mansoura, 2026)
**Project:** FitZone Sports — sports-equipment retail management system
**Reference:** *Section+1_Data+Mining.pdf*

This notebook covers:

1. Python fundamentals — variables, operators, conditions, loops, functions
2. The three assignments from the slides:
   1. **Grade calculator** (from a degree)
   2. **BMI calculator** — directly relevant to FitZone Sports' fitness customers
   3. **DataFrame queries** on the sample data from the slides

## 1. Python fundamentals — quick demo

In [1]:
# This is a comment.  Comments document code, do not affect execution.
print("Hello", "FitZone", sep=" - ")        # 'sep' separates the printed parts

# Variables and arithmetic operators
age = 22
print("age:", age, "next year:", age + 1)
print("plus 5:", age + 5, "  times 2:", age * 2,
      "  power 2:", age ** 2, "  div:", age / 3,
      "  int div:", age // 3, "  mod:", age % 3)

Hello - FitZone
age: 22 next year: 23
plus 5: 27   times 2: 44   power 2: 484   div: 7.333333333333333   int div: 7   mod: 1

In [2]:
# Comparison & logical operators
print(age > 18 and age < 65)
print(not (age == 22))

# If / elif / else
if age >= 18:
    print("adult")
elif age >= 13:
    print("teen")
else:
    print("kid")

True
False
adult

In [3]:
# while loop
i = 0
while i < 5:
    print("while", i)
    i += 1
print("---")

# for loop
for j in range(3):
    print("for", j)

while 0
while 1
while 2
while 3
while 4
---
for 0
for 1
for 2

In [4]:
# Functions
def greet(name, greeting="Hi"):
    """Return a greeting string."""
    return f"{greeting}, {name}!"

print(greet("Mohamed"))
print(greet("Ahmed", greeting="Welcome to FitZone"))

# Built-ins demo (input() is shown commented to keep the notebook non-interactive;
# uncomment it if you want to type a value when running interactively)
# n = int(input("type a number: "))
n = 5
for k in range(n):
    print("k =", k, "type =", type(k))

Hi, Mohamed!
Welcome to FitZone, Ahmed!
k = 0 type = <class 'int'>
k = 1 type = <class 'int'>
k = 2 type = <class 'int'>
k = 3 type = <class 'int'>
k = 4 type = <class 'int'>

## 2. Assignment 1 — Grade from degree

In [5]:
def assignment_1(name, department, degree):
    if   degree >= 85: grade = "Excellent"
    elif degree >= 75: grade = "Very Good"
    elif degree >= 65: grade = "Good"
    elif degree >= 50: grade = "Pass"
    else:              grade = "Fail"
    return f"Hello {name}, your department is {department} and your degree is {grade}!"

# Demo with hard-coded inputs (replace with input() if you want an interactive run)
print(assignment_1("Mohamed", "IS", 92))
print(assignment_1("Ahmed",   "IS", 78))
print(assignment_1("Yasmin",  "IS", 67))
print(assignment_1("Karim",   "IS", 54))
print(assignment_1("Omar",    "IS", 38))

Hello Mohamed, your department is IS and your degree is Excellent!
Hello Ahmed, your department is IS and your degree is Very Good!
Hello Yasmin, your department is IS and your degree is Good!
Hello Karim, your department is IS and your degree is Pass!
Hello Omar, your department is IS and your degree is Fail!

## 3. Assignment 2 — BMI calculator
A natural fit for FitZone Sports — many customers ask about which sports
equipment matches their fitness profile, and BMI is the first input the
in-store coach asks for.

In [6]:
def bmi_status(name, weight_kg, height_cm):
    height_m = height_cm / 100
    bmi = weight_kg / (height_m * height_m)
    if   bmi <= 18.5:                  status = "UNDERWEIGHT"
    elif 18.5 < bmi <= 24.9:           status = "NORMAL WEIGHT"
    elif 24.9 < bmi <= 29.9:           status = "OVERWEIGHT"
    else:                              status = "OBESE"
    return f"{name}, your BMI value is {bmi:.2f} and you are: {status}"

print(bmi_status("Mohamed", 70,  175))
print(bmi_status("Ahmed",   85,  178))
print(bmi_status("Yasmin",  55,  165))
print(bmi_status("Karim",   95,  180))

Mohamed, your BMI value is 22.86 and you are: NORMAL WEIGHT
Ahmed, your BMI value is 26.83 and you are: OVERWEIGHT
Yasmin, your BMI value is 20.20 and you are: NORMAL WEIGHT
Karim, your BMI value is 29.32 and you are: OVERWEIGHT

## 4. Assignment 3 — DataFrame operations

In [7]:
import pandas as pd

df = pd.DataFrame({
    "col1": [1, 2, 3, 4, 7],
    "col2": [4, 5, 6, 9, 5],
    "col3": [7, 8, 12, 1, 11],
})
df

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11

In [8]:
# (a) number of rows & columns
print("rows :", df.shape[0])
print("cols :", df.shape[1])

rows : 5
cols : 3

In [9]:
# (b) random 50% rows
df.sample(frac=0.5, random_state=1)

   col1  col2  col3
2     3     6    12
1     2     5     8

In [10]:
# (c) sort by col1 DESC
df.sort_values('col1', ascending=False)

   col1  col2  col3
4     7     5    11
3     4     9     1
2     3     6    12
1     2     5     8
0     1     4     7

In [11]:
# (d) filter where col2 >= 7
df.query('col2 >= 7')

   col1  col2  col3
3     4     9     1

In [12]:
# (e) oldest 3 rows = the last 3 rows of the frame
df.tail(3)

   col1  col2  col3
2     3     6    12
3     4     9     1
4     7     5    11

---
**End of Section 1 notebook.** All three assignments executed successfully.